### ISSUE TITLE
Sequence resolved calls in Parliament2 vcf file

### ISSUE THREAD

**Issue by MaestSi** [dnanexus/parliament2#55]
Dear Samantha,
I have noticed that Parliament2 vcf output (combined.genotyped.vcf) never contains sequence-resolved calls, even if the call is provided by Manta alone, which provides sequence-resolved calls instead (as in manta.svtyped.vcf file). Would it be possible in a future release to add sequence-resolved calls if there is no conflict between tools, since Manta is the only tool that provides sequence-resolved calls?
I never had svviz working within the Parliament2 framework, but it seems to me that it requires the calls to be sequence-resolved to plot graphics. Is it working only with deletions?
Moreover, with version 1.9 I have noticed that there is a survivor_sorted.vcf file, that seems to contain the same variants as combined.genotyped.vcf, but with the FILTER field always set to PASS. Is there a particular reason for that?

**Comment by AndrewCarroll** [comment]
Hi MaestSi,

Parliament2 should provide the raw manta output, which will contain those sequence resolved calls. However, you are right that most of the other methods don't have sequence resolution. For getting the sequence resolved calls, I think the best thing is to just go to the raw Manta output.

For svviz, since sequence resolution is required, only the deletions will be visualized.

For the v1.9 change, I am not sure why this occurred. I suspect it was by a user request (likely a paying DNAnexus user), but I could not speak to the reason why.
