### ISSUE TITLE
somatic SV

### ISSUE THREAD

**Issue by feihongloveworld** [dnanexus/parliament2#70]
hi sir：
   i want to find soamtic SV in Tumor_vs_Normal paired sample。
   can  parliament2 do this ？
thanks

**Comment by AndrewCarroll** [comment]
Parliament2 is not designed to perform tumor and normal paired samples. We have experimented with a customized workflow for this: (SVs in the tumor and normal separately, subtract SV calls present in the normal and then go back and force calls with SVTyper that are in the tumor but not the normal and subtract those). However, due to the complexity of this, I suggest using an individual method that is designed for somatic calling.

I will also point out that the main maintainer of Parliament2, Samantha Zarate, is not a sir.
